### ISSUE TITLE
Cant' Build Build KalavarDB on Windows 10

### ISSUE THREAD

**Issue by Tembocs** [KalavarDB/core#27]
**Describe the bug**
I just cloned the KavavarDB/Core and called `cargo build` and got the following error message
```cmd
The following warnings were emitted during compilation:

warning: "jemalloc support for `x86_64-pc-windows-msvc` is untested"

error: failed to run custom build command for `jemalloc-sys v0.3.2`

Caused by:
  process didn't exit successfully: `D:\qnd\rust\core\target\debug\build\jemalloc-sys-81a3c5ae37730a48\build-script-build` (exit code: 101)
  --- stdout
  TARGET=x86_64-pc-windows-msvc
  HOST=x86_64-pc-windows-msvc
  NUM_JOBS=8
  OUT_DIR="D:\\qnd\\rust\\core\\target\\debug\\build\\jemalloc-sys-e5fdcc6165859f6f\\out"
  BUILD_DIR="D:\\qnd\\rust\\core\\target\\debug\\build\\jemalloc-sys-e5fdcc6165859f6f\\out\\build"
  SRC_DIR="C:\\Users\\Amani\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.3.2"
  cargo:warning="jemalloc support for `x86_64-pc-windows-msvc` is untested"
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_x86_64-pc-windows-msvc = None
  CC_x86_64_pc_windows_msvc = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-msvc = None
  CFLAGS_x86_64_pc_windows_msvc = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  CC="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe"
  CFLAGS="-nologo -MD -Z7 -Brepro -W4"
  JEMALLOC_REPO_DIR="jemalloc"
  JEMALLOC_SRC_DIR="D:\\qnd\\rust\\core\\target\\debug\\build\\jemalloc-sys-e5fdcc6165859f6f\\out\\jemalloc"
  cargo:rustc-cfg=prefixed
  --with-jemalloc-prefix=_rjem_
  running: "sh" "D:/qnd/rust/core/target/debug/build/jemalloc-sys-e5fdcc6165859f6f/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-pc-win32" "--build=x86_64-pc-win32" "--prefix=D:\\qnd\\rust\\core\\target\\debug\\build\\jemalloc-sys-e5fdcc6165859f6f\\out"
  checking for xsltproc... /c/ProgramData/Anaconda3/Library/bin/xsltproc
  checking for x86_64-pc-win32-gcc... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe
  checking whether the C compiler works... no

  --- stderr
  configure: error: in `/d/qnd/rust/core/target/debug/build/jemalloc-sys-e5fdcc6165859f6f/out/build':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  thread 'main' panicked at 'command did not execute successfully: "sh" "D:/qnd/rust/core/target/debug/build/jemalloc-sys-e5fdcc6165859f6f/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-pc-win32" "--build=x86_64-pc-win32" "--prefix=D:\\qnd\\rust\\core\\target\\debug\\build\\jemalloc-sys-e5fdcc6165859f6f\\out"
  expected success, got: exit code: 77', C:\Users\Amani\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.3.2\build.rs:392:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**
I'm on Windows 10 64x build 21296.1000
1. Clone the `kavalar/core`
2. Call `cargp build`
3. Then at the some point of building you will see this error message

**Comment by AltriusRS** [comment]
Hi there, I am aware that Jemalloc does not compile on windows, I need to work on a way of managing memory on windows platforms using built in methods of the OS (im looking into `windows-rs` at the current moment in time

A simple fix for this issue would be to restrict the use of Jemalloc and any Jemalloc dependant packages and modules to non-windows build targets.

Ill push a patch which should fix those problems in the next 24 hours or so.

Thanks for showing interest in the project, its really great to see people getting involved.

**Comment by ChillFish8** [comment]
Would recommend setting up WSL2 properly and linking it to your terminal so its easier to work with on windows, as an alternative it might be worth locally tracking data usage rather than specifically using Jemalloc (possibly as a fallback) as you should still be able to get accurate reading on usage.

**Comment by AltriusRS** [comment]
> "Would recommend setting up WSL2 properly and linking it to your terminal so its easier to work with on windows"

This is actually something I began doing today whilst bored at college, so ill keep at it


> "as an alternative it might be worth locally tracking data usage rather than specifically using Jemalloc (possibly as a fallback) as you should still be able to get accurate reading on usage."

I'm not sure what you are implying here, are you saying that we should use a custom allocator which tracks memory usage across all platforms in the same way, or are you saying that we should attempt to track memory usage using custom code which looks at OS provided statistics? Could you please clarify your meaning?

**Comment by ChillFish8** [comment]
I mean more tracking the size of the cache stores themselves, this could be via a custom allocator or atleasta basic wrapper over the default, i dont think you would nessesarly need it to be global as your main aim is tracking the size of the cached data etc... no?

**Comment by AltriusRS** [comment]
due to the un-sized nature of the data types at play within said cached data, i actually think i have found a solution to the problem, by using the `procinfo` crate it (appears that it) is possible to track the memory usage of the process as a whole which is preferred over writing a cutom allocator, at least at the current stage. This would basically provide all the functionality for all the platforms we are targeting, and wouldnt require any fancy custom allocator tricks.

Im going to push a jemalloc-less commit to the branch and close the issue for now, but people are welcome to continue providing ideas and feedback
